sudo: required
dist: trusty

language: node_js

node_js:
    - "6.3"
python:
    - "3.4"

services:
    - docker

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      # nodejs >v4 compiler requirements
      - g++-4.8
      - openjdk-7-jdk

before_install:
    - npm -v
    - node -v

install:
    - cd src/hasher
    - npm install
    - cd ../rng
    - npm install
    - cd ../webui
    - npm install
    - cd ../worker

script:
    - echo "No tests"

after_success:
    - export REPO_HASH=richardcase/dockercoins-hasher
    - export REPO_RNG=richardcase/dockercoins-rng
    - export REPO_WEB=richardcase/dockercoins-webui
    - export REPO_WORK=richardcase/dockercoins-worker
    - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
    - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
    - cd ../hasher
    - docker build -f  Dockerfile -t $REPO_HASH:$COMMIT .
    - docker tag $REPO_HASH:$COMMIT $REPO_HASH:$TAG
    - docker tag $REPO_HASH:$COMMIT $REPO_HASH:travis-$TRAVIS_BUILD_NUMBER
    - docker push $REPO_HASH
    - cd ../rng
    - docker build -f  Dockerfile -t $REPO_RNG:$COMMIT .
    - docker tag $REPO_RNG:$COMMIT $REPO_RNG:$TAG
    - docker tag $REPO_RNG:$COMMIT $REPO_RNG:travis-$TRAVIS_BUILD_NUMBER
    - docker push $REPO_RNG
    - cd ../webui
    - docker build -f  Dockerfile -t $REPO_WEB:$COMMIT .
    - docker tag $REPO_WEB:$COMMIT $REPO_WEB:$TAG
    - docker tag $REPO_WEB:$COMMIT $REPO_WEB:travis-$TRAVIS_BUILD_NUMBER
    - docker push $REPO_WEB
    - cd ../worker
    - docker build -f  Dockerfile-netcore -t $REPO_WORK:$COMMIT .
    - docker tag $REPO_WORK:$COMMIT $REPO_WORK:$TAG
    - docker tag $REPO_WORK:$COMMIT $REPO_WORK:travis-$TRAVIS_BUILD_NUMBER
    - docker push $REPO_WORK

env:
    global:
        - CXX=g++-4.8
        - NODE_ENV=development
        - COMMIT=${TRAVIS_COMMIT::8}