version: "2"

services:
  rng:
    build: src/rng
    ports:
      - "8002"
    networks:
      - backend
    depends_on:
      - redis

  hasher:
    build: src/hasher
    ports:
      - "8001"
    networks:
      - backend
    depends_on:
      - redis

  webui:
    build: src/webui
    ports:
      - "8000:8000"
    networks:
      - frontend
    volumes:
      - "./src/webui/files/:/files/"
    depends_on:
      - redis

  redis:
    image: redis
    ports: 
      - "6379:6379"
    networks:
      - backend
      - frontend

  worker:
    build: 
      context: src/worker
      dockerfile: Dockerfile
    networks:
      - backend
    depends_on:
      - redis
      - rng
      - hasher

networks:
  backend:
  frontend: