version: "2"

services:
  rng:
    build: rng
    ports:
      - "8002:8002"
    depends_on:
      - redis

  hasher:
    build: hasher
    ports:
      - "8001:8001"
    depends_on:
      - redis

  webui:
    build: webui
    ports:
      - "8000:8000"
    volumes:
      - "./webui/files/:/files/"
    depends_on:
      - redis

  redis:
    image: redis

  worker:
    build: worker
    depends_on:
      - redis