version: "2"

services:
  rng:
    build: code\src\rng
    ports:
      - "8002"
    networks:
      - backend
    depends_on:
      - redis

  hasher:
    build: code\src\hasher
    ports:
      - "8001"
    networks:
      - backend
    depends_on:
      - redis

  webui:
    build: code\src\webui
    ports:
      - "8000:8000"
    networks:
      - frontend
    volumes:
      - "./code/src/webui/files/:/files/"
    depends_on:
      - redis

  redis:
    build: code\src\redis
    ports: 
      - "6379"
    networks:
      - backend
      - frontend

  worker:
    #build: worker
    build: 
      context: code\src\worker
      #dockerfile: Dockerfile-go
      dockerfile: Dockerfile-python
    networks:
      - backend
    depends_on:
      - redis
      - rng
      - hasher

networks:
  backend:
  frontend: